Feature/models tweaking and testing
softwareatelier4/Group1 pull request #4
Opened 2017-03-15 16:38 UTC by CrashingBrain

Please approve and take vision of the new Models <3

2017-03-15 16:44 UTC, BalestraPatrick requested changes

2017-03-15 16:44 UTC, BalestraPatrick commented on models/Freelance.js
> +		urlPic				: { type: String },
Would you mind naming this property `urlPicture`?

2017-03-15 16:44 UTC, BalestraPatrick commented on models/Freelance.js
> +	if ( this.avgScore !== undefined ){
Could you please format the code in the usual way like it was before? `if (this.avgScore !== undefined) {`

2017-03-15 16:51 UTC, Generalbrus commented on models/Freelance.js
> +	if ( this.price !== undefined ){
space after `)` thanks

2017-03-15 16:51 UTC, Generalbrus commented on models/Freelance.js
> +		} else{
space after `else` thanks

2017-03-15 16:52 UTC, Generalbrus commented on models/Review.js
> +		if(length>1000){
spaces

2017-03-15 16:54 UTC, Generalbrus commented on models/Tag.js
> +Tag.pre('save', function (next) {
no space after `function` thanks

2017-03-15 17:32 UTC, aronfiechter requested changes
Please really let's make Title a required field, so that a basic Freelancer Profile has:

**[Job Title - Name]**
*email*

2017-03-15 17:32 UTC, Spyridox commented on models/Freelance.js
> +		title					: { type: String },
Can we please make `title` a required property? As said, it's as important as the `firstName`.
A practical reason is: a person that wants to make two profiles for two different jobs, maybe both in the same category.

2017-03-15 17:32 UTC, Spyridox commented on models/Freelance.js
> +		tags					: [{ type: ObjectID, default: [] }],
We should add `ref: "Tag", ` similarly to how `reviews` is.

2017-03-15 17:32 UTC, Spyridox commented on seed_data/seedData.js
> +      "title"       : "President Candidate",
Not really a "job" that a freelancer can offer. What would you hire a `President Candidate` for (except making America great again)?

2017-03-15 17:32 UTC, Spyridox commented on seed_data/seedData.js
> +      "title"       : "Blogger",
Is "Blogger" a job you can pay someone to do for you?

2017-03-15 19:43 UTC, Generalbrus commented on seed_data/seedData.js
> +      "title"       : "President Candidate",
Isn't it `Presidential Candidate` anyway?

2017-03-15 19:44 UTC, Generalbrus commented on seed_data/seedData.js
> +      "title"       : "Blogger",
Yes, int the content writer sense - anyway that's up to the user so
Why are categories hard coded - unlike tags?

2017-03-15 20:22 UTC, CrashingBrain commented on models/Freelance.js
> +		urlPic				: { type: String },
done

2017-03-15 20:22 UTC, CrashingBrain commented on models/Freelance.js
> +	if ( this.avgScore !== undefined ){
done

2017-03-15 20:22 UTC, CrashingBrain commented on models/Freelance.js
> +	if ( this.price !== undefined ){
done

2017-03-15 20:23 UTC, CrashingBrain commented on models/Freelance.js
> +		} else{
done

2017-03-15 20:23 UTC, CrashingBrain commented on models/Review.js
> +		if(length>1000){
done

2017-03-15 20:23 UTC, CrashingBrain commented on models/Tag.js
> +Tag.pre('save', function (next) {
done

2017-03-15 20:23 UTC, CrashingBrain commented on models/Freelance.js
> +		title					: { type: String },
ok. done

2017-03-15 20:23 UTC, CrashingBrain commented on models/Freelance.js
> +		tags					: [{ type: ObjectID, default: [] }],
yep. right. done.

2017-03-16 00:03 UTC, aronfiechter approved these changes

2017-03-16 00:21 UTC, merged