Feature/view homepage
softwareatelier4/Group1 pull request #8
Opened 2017-03-17 18:02 UTC by zuccha

Homepage done.

2017-03-17 18:37 UTC, lazy-val reviewed
Could you add some comments in the react part or explain us next week how it works?

2017-03-17 18:37 UTC, Shelyo commented on public/components/homepage.js
> +        searchWarning.innerHTML = "Only alphabetic characters allowed.";
Just a as a note: Maybe also allow numbers in the future if somebody wants for example an HTML5 developer.

2017-03-17 18:37 UTC, Shelyo commented on public/css/freelancer-create.css
> +  margin: 10vh 10vw 5vh 10vw;
You could use the shorter version `margin:  10vh 10vw 5vh` here

2017-03-17 18:37 UTC, Shelyo commented on public/css/freelancer-create.css
> +  margin-bottom:45px;
Space after ':'

2017-03-17 18:37 UTC, Shelyo commented on public/css/freelancer-create.css
> +  outline:none;
Space after the colon.

2017-03-17 18:37 UTC, Shelyo commented on public/css/freelancer-create.css
> +  margin-bottom:45px;
Also, tags are a bit too rounded considering that no other element on a job listing view page has rounded corners.

2017-03-17 19:32 UTC, aronfiechter requested changes
Minor things to be changed mainly in the create form requirements.

However there seems to be a problem on the homepage after more freelancers are POSTed to the database: no freelancer is rendered anymore. Somehow, the GET:/search returns the freelancers but none is there to be rendered.

2017-03-17 19:32 UTC, aronfiechter commented on public/components/freelancer-create.js
> +        <div className="freelancer-form">
Maybe one indent too much here (on the whole html).

2017-03-17 19:32 UTC, aronfiechter commented on public/components/homepage.js
> +        <input id="search-name" placeholder="Who?" onKeyDown={this.searchRequest} />
Instead of "Who?" I'd ask "What do you need?" or "Who do you need?" or "What service do you need?"; something that implies that you can (and should) search mainly for a work title, and we'll return all the people related to it.

2017-03-17 19:32 UTC, aronfiechter commented on public/components/freelancer-create.js
> +                <input ref="familyName" className="family-name" name="family-name" type="text" required/>
As in the Model, familyName is not required.

2017-03-17 19:32 UTC, aronfiechter commented on public/components/freelancer-create.js
> +                <option value="selected" disabled>Please select a job category</option>
For some reason here it shows "test category 2" as already selected and doesn't show the hint.
Also in the model it is not required but maybe we should make it required.

2017-03-17 19:32 UTC, aronfiechter commented on public/components/freelancer-create.js
> +              <input ref="phone" className="phone" name="phone" type="text" required/>
Not required in the model.

2017-03-17 19:32 UTC, aronfiechter commented on public/components/freelancer-create.js
> +            <input type="submit" value="Submit"/>
Should add redirect to home after creation (idk where it should be done, otherwise the user might think it didn't work [as I did, and I posted myself 5 times to the db]).

2017-03-17 19:44 UTC, Spyridox commented on public/components/homepage.js
> +        urlPicture={this.props.freelancers[i].urlPicture}
Spaces around =, for next lines too

2017-03-17 20:15 UTC, zuccha commented on public/components/homepage.js
> +        searchWarning.innerHTML = "Only alphabetic characters allowed.";
I was asked not to include numbers, so for the moment I'll leave as it is, but I see that it could be useful.

2017-03-17 20:16 UTC, Spyridox commented on public/components/homepage.js
> +          <span>Average Score: {this.props.avgScore} in 5</span>
I'd write `{this.props.avgScore || -}/5`, similar to freelancer-view. (`|| -` for the case in which there's no score.)

2017-03-17 20:19 UTC, Spyridox commented on public/components/homepage.js
> +          <span>Average Score: {this.props.avgScore} in 5</span>
Actually the `|| -` doesn't work, use `|| "-"`.

2017-03-17 20:53 UTC, zuccha commented on public/components/homepage.js
> +          <span>Average Score: {this.props.avgScore} in 5</span>
Done.

2017-03-17 20:53 UTC, zuccha commented on public/components/homepage.js
> +        urlPicture={this.props.freelancers[i].urlPicture}
Done.

2017-03-17 20:54 UTC, zuccha commented on public/components/homepage.js
> +        <input id="search-name" placeholder="Who?" onKeyDown={this.searchRequest} />
Done.

2017-03-17 20:58 UTC, zuccha commented
Reviews about `freelancer-create.js` and `freelancer-create.css` should go into the `create-view` branch.

2017-03-17 21:02 UTC, aronfiechter approved these changes

2017-03-18 18:10 UTC, merged

2017-03-19 16:10 UTC, Generalbrus commented on public/components/freelancer-create.js
> +            <input type="submit" value="Submit"/>
it redirects already to the created freelancer

2017-03-19 16:43 UTC, Spyridox commented on public/components/freelancer-create.js
> +            <input type="submit" value="Submit"/>
Yup, now it does.

2017-03-19 16:45 UTC, Generalbrus commented on public/components/freelancer-create.js
> +        <div className="freelancer-form">
k

2017-03-19 16:45 UTC, Generalbrus commented on public/css/freelancer-create.css
> +  outline:none;
k

2017-03-19 16:45 UTC, Generalbrus commented on public/css/freelancer-create.css
> +  margin: 10vh 10vw 5vh 10vw;
k